version: '3.8'

services:
  essen-api:
    build:
      context: .
      dockerfile: deploy/docker/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      # Mount source code for live reload during development
      - ./src:/app/src:ro
      # Mount data directory for cache persistence
      - ./data:/app/data
    environment:
      - PYTHONUNBUFFERED=1
    command: uvicorn src.api.main:app --host 0.0.0.0 --port 8000 --reload
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/health', timeout=5)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
