apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: essen-api-cache
  namespace: essen
  labels:
    app: essen-route-planning
    component: cache
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 5Gi
